version: '2'
services:
    node:
        image: node
        container_name: container-nodejs
        volumes:
            - .:/src
        working_dir: /src
        depends_on:
            - selenium-hub
        command: tail -f /dev/null

    selenium-hub:
        image: selenium/hub:2.53.1
        container_name: selenium-hub
        privileged: true
        ports:
            - 4444:4444
        environment:
            - GRID_TIMEOUT=240000
            - GRID_BROWSER_TIMEOUT=240000
        networks:
            - selenium-hub_grid_internal

    nodechrome:
        image: selenium/node-chrome-debug:2.53.1-americium
        container_name: selenium-chrome
        privileged: true
        depends_on:
            - selenium-hub
        ports:
            - 5900
        environment:
            - no_proxy=localhost
            - TZ=Europe/Lisbon
            - HUB_PORT_4444_TCP_ADDR=selenium-hub
            - HUB_PORT_4444_TCP_PORT=4444
        networks:
            - selenium-hub_grid_internal

    nodefirefox:
        image: selenium/node-firefox-debug:2.53.1
        container_name: selenium-firefox
        privileged: true
        depends_on:
            - selenium-hub
        ports:
            - 5901
        environment:
            - no_proxy=localhost
            - TZ=Europe/Lisbon
            - HUB_PORT_4444_TCP_ADDR=selenium-hub
            - HUB_PORT_4444_TCP_PORT=4444
        networks:
            - selenium-hub_grid_internal
        
networks:
    selenium-hub_grid_internal: