version: '2'
services:
    nodejs:
        image: node
        volumes:
            - .:/src
        working_dir: /src
        depends_on:
            - progrid
        command: tail -f /dev/null

    progrid:
        image: selenium/hub:2.53.1
        container_name: progrid
        privileged: true
        ports:
            - 4444:4444
        environment:
            - GRID_TIMEOUT=240000
            - GRID_BROWSER_TIMEOUT=240000
        networks:
            - progrid_grid_internal

    nodechrome:
        image: selenium/node-chrome-debug:2.53.1-americium
        privileged: true
        depends_on:
            - progrid
        ports:
            - 5900
        environment:
            - no_proxy=localhost
            - TZ=Europe/Lisbon
            - HUB_PORT_4444_TCP_ADDR=progrid
            - HUB_PORT_4444_TCP_PORT=4444
        networks:
            - progrid_grid_internal

    nodefirefox:
        image: selenium/node-firefox-debug:2.53.1
        privileged: true
        depends_on:
            - progrid
        ports:
            - 5901
        environment:
            - no_proxy=localhost
            - TZ=Europe/Lisbon
            - HUB_PORT_4444_TCP_ADDR=progrid
            - HUB_PORT_4444_TCP_PORT=4444
        networks:
            - progrid_grid_internal
        
networks:
    progrid_grid_internal: