version: "3"
services:
  api:
    image: node
    ports:
      - 3000:3000
    volumes: 
      - .:/src
    depends_on:
      - selenium-hub
    working_dir: /src
    command: tail -f /dev/null
    command: bash -c "npm install && npm start"
  
  selenium-hub:
    image: selenium/hub:3.141.59-selenium
    container_name: selenium-hub
    ports:
      - "4444:4444"
  chrome:
    image: selenium/node-chrome:3.141.59-selenium
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
  firefox:
    image: selenium/node-firefox:3.141.59-selenium
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444